/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        gray: {
          100: '#ffffff',
          200: '#e3e3e3',
          300: '#cbcfd4',
          400: '#b2b8be',
          500: '#9ca1a7',
          600: '#868b91',
          700: '#70767b',
          800: '#515151',
          900: '#1e1e1e',
          1000: '#000000',
        },
        red: {
          100: '#ffe7ea',
          200: '#ffc5c6',
          300: '#fda2a3',
          400: '#f77d82',
          500: '#ed5562',
          600: '#cf3e4c',
          700: '#ac2e39',
          800: '#8a1e28',
          900: '#690e17',
          1000: '#4b0000',
        },
        green: {
          100: '#d7ffe3',
          200: '#aee9d8',
          300: '#82d3b3',
          400: '#51bd8e',
          500: '#30a471',
          600: '#258a59',
          700: '#1a7143',
          800: '#0e582d',
          900: '#034118',
          1000: '#002b00',
        },
        neon: {
          DEFAULT: '#e8ff00',
          100: '#fdfff2',
          200: '#f9ffe0',
          600: '#e8ff00',
        },
        content: {
          primary: '#172b4d',
          secondary: '#626f86',
        },
        background: '#000000',
        foreground: '#172b4d',
        card: {
          DEFAULT: '#ffffff',
          foreground: '#172b4d',
        },
        primary: {
          DEFAULT: '#ed5562',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: '#e3e3e3',
          foreground: '#172b4d',
        },
        muted: {
          DEFAULT: '#e3e3e3',
          foreground: '#626f86',
        },
        accent: {
          DEFAULT: '#ffe7ea',
          foreground: '#ac2e39',
        },
        destructive: {
          DEFAULT: '#cf3e4c',
          foreground: '#ffffff',
        },
        border: '#cbcfd4',
        input: '#e3e3e3',
        ring: '#ed5562',
      },
      fontFamily: {
        display: ['ClashDisplay-Bold'],
        'display-regular': ['ClashDisplay-Semibold'],
        'display-semibold': ['ClashDisplay-Semibold'],
        heading: ['Panchang-Bold'],
        'heading-regular': ['Panchang-Regular'],
        'heading-semibold': ['Panchang-Bold'],
        sans: ['Inter_400Regular'],
        'sans-medium': ['Inter_600SemiBold'],
        'sans-semibold': ['Inter_600SemiBold'],
        'sans-bold': ['Inter_600SemiBold'],
      },
      fontSize: {
        'display-lg': ['96px', { lineHeight: '104px', letterSpacing: '-1px' }],
        'display-md': ['52px', { lineHeight: '64px', letterSpacing: '-1px' }],
        'display-sm': ['44px', { lineHeight: '52px', letterSpacing: '0px' }],
        'display-xs': ['36px', { lineHeight: '44px', letterSpacing: '0px' }],
        'heading-2xl': ['40px', { lineHeight: '52px', letterSpacing: '0px' }],
        'heading-xl': ['36px', { lineHeight: '44px', letterSpacing: '0px' }],
        'heading-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px' }],
        'heading-md': ['28px', { lineHeight: '36px', letterSpacing: '0px' }],
        'heading-sm': ['24px', { lineHeight: '32px', letterSpacing: '0px' }],
        'heading-xs': ['20px', { lineHeight: '28px', letterSpacing: '0px' }],
        'label-lg': ['18px', { lineHeight: '24px', letterSpacing: '0.3px' }],
        'label-md': ['16px', { lineHeight: '20px', letterSpacing: '0.3px' }],
        'label-sm': ['14px', { lineHeight: '16px', letterSpacing: '0.3px' }],
        'label-xs': ['12px', { lineHeight: '16px', letterSpacing: '0.3px' }],
        'paragraph-lg': [
          '18px',
          { lineHeight: '28px', letterSpacing: '0.3px' },
        ],
        'paragraph-md': [
          '16px',
          { lineHeight: '24px', letterSpacing: '0.3px' },
        ],
        'paragraph-sm': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.3px' },
        ],
        'paragraph-xs': [
          '12px',
          { lineHeight: '20px', letterSpacing: '0.3px' },
        ],
      },
      borderRadius: {
        lg: '10px',
        md: '8px',
        sm: '6px',
      },
    },
  },
  plugins: [],
};
